cookie:
  expiry_days: 30
  key: signature_key
  name: diet_cookie
credentials:
  usernames:
    admin:
      name: "\uAD00\uB9AC\uC790"
      password: $2b$12$khzPIlhKD4F6M8oOF6FO6u3o21rLUTPtw0rwU.64RHe8NfQ04590K
preauthorized:
  emails: []
